version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-volume:/data/db
      - ./data/database/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./data/database/nft-db-dump:/nft-db-dump

volumes:
  mongo-volume:
