version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - EXPRESS_MONGO_URI=mongodb://mongo:27017/nft-db
      - EXPRESS_HOST=0.0.0.0
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-volume:/data/db
      - ./data/database/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./data/database/nft-db-dump:/nft-db-dump

volumes:
  mongo-volume:
